server:
  port: 4004


  spring:
    cloud:
      gateway:
        routes:
          - id: patient-service-route
            uri: http://patient-service:4000
            predicates:
              - path=/api/patient/**
            filters:
              -strip-prefix=1


            ## Rest Client -> http://localhost:4004/api/patients
            ## Api Gateway -> http://patient-service/4000     {strip removes api from url}
            ## Patient Service (SPTING BOOT APP) -> /patients ->Patients array


          - id: api-docs-patient-routes
            uri: http://patient-service:4000
            predicates:
              - patth=/api/api-docs/patients
            filters:
              - rewrite-path=/api-docs/patients,/v3/api-docs


            ## REST-CLIENT -> http://localhost:4004/api-docs/patients
            ## API-GATEWAT -> http://patient-service:4000/v3/api-docs